apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-sample-5
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: dotnet-sample-5
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/kadourah/dotnet-sample-5
      ref:
        branch: main
