apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-dotnet-app-5
  labels:
    apps.tanzu.vmware.com/has-tests:  true
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sample-dotnet-app-5
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: dotnet
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/kadourah/dotnet-sample-5
      ref:
        branch: main
